export const API_REDUCERS = [
	"registrationApi",
	"authenticationApi",
	"userPurposeApi",
	"cityApi",
	"profileApi",
	"interestApi",
	"userInterestsApi",
	"profileMediaApi",
	"profileAboutApi",
	"likeApi",
	"matchApi",
	"pingApi",
	"profileQualityApi",
	"complaintApi",
	"subscribeApi",
] as const;

export const API_MIDDLEWARES = [
	"userPurposeApi",
	"authenticationApi",
	"cityApi",
	"registrationApi",
	"profileApi",
	"interestApi",
	"userInterestsApi",
	"profileMediaApi",
	"profileAboutApi",
	"interactionApi",
	"matchApi",
	"pingApi",
	"profileQualityApi",
	"complaintApi",
	"subscribeApi",
] as const;
